Glue42/core

- docs/core/03_tutorials/tutorials.md
Signed-off-by: 3lmo <emi.petkov@gmail.com>
> refactor(GLUEC-44): typos

- README.md
Signed-off-by: 3lmo <emi.petkov@gmail.com>
> refactor(GLUEC-44): core to glue42-core

- README.md
Signed-off-by: 3lmo <emi.petkov@gmail.com>
> refactor(GLUEC-44): rename links glue42-core to core

- docs/core/01_what-is-glue42-core/01_introduction/introduction.md
- docs/core/01_what-is-glue42-core/03_core-concepts/01_environment/environment.md
- docs/core/01_what-is-glue42-core/03_core-concepts/03_cli/cli.md
- docs/core/02_getting-started/02_setting-environment/02_multiple-applications/multiple-applications.md
Fix a couple of mistakes in the documentation.
> docs: fix mistakes

- packages/cli-core/README.md
- packages/web/readme.md
> Added readme texts for cli-core and web packages

- packages/cli-core/src/builder/controller.ts
> Fixed an issue where the CLI `build` will produce a .js config file, instead of .json

- packages/web/src/index.ts
> remove GlueCore from window object

- live-examples/windows/window-events/index.html
- scripts/live-examples/reload-code-sandboxes.js
Signed-off-by: suzunov <stoyan.uzunov@tick42.com>
> Fixed code-sandbox urls in reload script.

- live-examples/windows/window-events/app-a/index.js
- live-examples/windows/window-events/app-b/index.js
Signed-off-by: suzunov <stoyan.uzunov@tick42.com>
> Improved window-events example. Excluding my window from logs.

- live-examples/contexts/context-discovery/app-b/index.html
- live-examples/contexts/context-subscription/app-a/index.js
- live-examples/interop/method-discovery-by-event/app-a/index.js
- live-examples/interop/method-discovery-by-event/app-b/index.js
- live-examples/interop/method-discovery-by-event/app-c/index.js
- live-examples/interop/method-discovery-by-name/app-a/index.js
- live-examples/interop/method-discovery-by-name/app-b/index.js
- live-examples/interop/method-discovery-by-name/app-c/index.js
- live-examples/interop/server-discovery/app-a/index.js
- live-examples/interop/server-discovery/app-b/index.js
- live-examples/interop/server-discovery/app-c/index.js
- live-examples/interop/stream-pub-sub/app-a/index.html
- live-examples/interop/stream-pub-sub/app-a/index.js
- live-examples/windows/window-events/app-a/index.js
- live-examples/windows/window-opening/app/index.js
Signed-off-by: suzunov <stoyan.uzunov@tick42.com>
> Live examples - clearing form fields, improvements

- docs/core/03_capabilities/04_window-management/window-management.md
- live-examples/contexts/context-discovery/index.html
- live-examples/contexts/context-get-set/index.html
- live-examples/contexts/context-subscription/index.html
- live-examples/interop/basic-interop/index.html
- live-examples/interop/invocation-target/index.html
- live-examples/interop/method-discovery-by-event/index.html
- live-examples/interop/method-discovery-by-name/index.html
- live-examples/interop/server-discovery/index.html
- live-examples/interop/stream-events/index.html
- live-examples/interop/stream-pub-sub/index.html
- live-examples/interop/stream-subscription-request/index.html
- live-examples/windows/window-events/index.html
- live-examples/windows/window-opening/index.html
Signed-off-by: suzunov <stoyan.uzunov@tick42.com>
> live-examples - applications loaded in iframes on default page

- tutorials/guides/react/react.md
- tutorials/react/solution/Clients/package-lock.json
- tutorials/react/solution/Clients/package.json
- tutorials/react/solution/Clients/src/ChannelSelectorWidget.js
- tutorials/react/solution/Clients/src/Clients.jsx
- tutorials/react/solution/Clients/src/constants.js
- tutorials/react/solution/Clients/src/glue.js
- tutorials/react/solution/Stocks/package-lock.json
- tutorials/react/solution/Stocks/package.json
- tutorials/react/solution/Stocks/src/ChannelSelectorWidget.js
- tutorials/react/solution/Stocks/src/StockDetails.jsx
- tutorials/react/solution/Stocks/src/Stocks.jsx
- tutorials/react/solution/Stocks/src/constants.js
- tutorials/react/solution/Stocks/src/glue.js
- tutorials/react/solution/glue.config.json
- tutorials/react/start/Clients/package.json
- tutorials/react/start/Clients/src/ChannelSelectorWidget.js
- tutorials/react/start/Stocks/package.json
- tutorials/react/start/Stocks/src/ChannelSelectorWidget.js
Signed-off-by: GrigorPenev <grinit43@gmail.com>
> Extend ReactJS documentation and tutorial with channels

- packages/web/package-lock.json
- packages/web/src/shared/promise-plus.ts
- packages/web/src/web.ts
> Improved the web initialization with timeout logic and shared worker check.

- docs/core/03_capabilities/02_application-management/application-management.md
- docs/core/03_capabilities/99_fdc3-compliancy/fdc3-compliancy.md
- tutorials/guides/02_core/01_javascript/javascript.md
- tutorials/javascript/solution/client-details/index.js
- tutorials/javascript/solution/glue.config.dev.json
- tutorials/javascript/solution/glue.config.json
- tutorials/javascript/solution/glue.layouts.json
- tutorials/javascript/solution/stocks/details/index.js
- tutorials/javascript/solution/stocks/index.js
- tutorials/javascript/start/Clients/index.html
- tutorials/javascript/start/Clients/index.js
- tutorials/javascript/start/Stocks/details/index.js
- tutorials/javascript/start/Stocks/index.html
- tutorials/javascript/start/Stocks/index.js
- tutorials/javascript/start/client-details/index.html
- tutorials/javascript/start/client-details/index.js
> Edited FDC3 docs and JS Tutorial Workspaces chapter

- package-lock.json
- package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/rollup.config.js
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/rollup.config.js
Fixes dependency vulnerabilities detected in root, web and core.
> Vulnerability fixes

- packages/fdc3/src/agent.ts
- packages/fdc3/src/channels/channels.ts
- packages/fdc3/src/index.ts
- packages/fdc3/src/main.ts
- packages/fdc3/src/types/glue42gd.d.ts
- packages/fdc3/src/types/windowtype.d.ts
- packages/fdc3/src/utils.ts
Improve the initialization performance
Skip initailizing FDC3 when running inside of an autoInject: true environment
> Consider the glue42gd.fdc3InitsGlue flag

- packages/fdc3/package-lock.json
- packages/golden-layout/package-lock.json
- packages/golden-layout/package.json
> Remove stale dependencies from the lock files

- docs/core/03_capabilities/03_intents/intents.md
- docs/core/04_core-concepts/02_environment/01_overview/overview.md
- docs/core/04_core-concepts/02_environment/02_setup/setup.md
- docs/core/06_tutorials/tutorials.md
- docs/core/07_faq/faq.md
- packages/web/web.d.ts
- packages/workspaces-api/workspaces.d.ts
- tutorials/guides/02_core/01_javascript/javascript.md
> Fixed broken links

- docs/core/03_capabilities/99_fdc3-compliance/fdc3-compliance.md
- packages/fdc3/src/channels/channels.ts
- packages/fdc3/src/main.ts
Rename the branch inside of the FDC3 code demo link
> Fix a race in the @glue42/fdc3 Glue42 Enterprise channel sync

- docs/core/04_core-concepts/01_web-platform/01_overview/overview.md
- docs/core/04_core-concepts/02_web-client/03_react/react.md
- docs/core/04_core-concepts/02_web-client/04_angular/angular.md
> Edited the React and Angular wrappers docs

- packages/web-platform/platform.d.ts
- packages/web-platform/src/factory.ts
- packages/web/src/config/index.ts
- packages/web/src/web.ts
> Added ClientOnly mode for the platform

- packages/web-platform/platform.d.ts
- packages/web-platform/src/common/types.ts
- packages/web-platform/src/controllers/main.ts
- packages/web-platform/src/controllers/session.ts
- packages/web-platform/src/controllers/system.ts
- packages/web-platform/src/index.ts
- packages/web-platform/src/libs/applications/appStore/directory.ts
- packages/web-platform/src/libs/applications/appStore/remoteWatcher.ts
- packages/web-platform/src/libs/applications/controller.ts
- packages/web-platform/src/libs/applications/decoders.ts
- packages/web-platform/src/libs/applications/defaults.ts
- packages/web-platform/src/libs/applications/types.ts
- packages/web-platform/src/libs/channels/controller.ts
- packages/web-platform/src/libs/intents/controller.ts
- packages/web-platform/src/libs/layouts/controller.ts
- packages/web-platform/src/libs/windows/controller.ts
- packages/web-platform/src/libs/workspaces/controller.ts
- packages/web-platform/src/shared/decoders.ts
- packages/web-platform/src/shared/fetchTimeout.ts
- packages/web-platform/src/shared/ioc.ts
- packages/web/src/appManager/controller.ts
- packages/web/src/index.ts
- packages/web/src/shared/ioc.ts
- packages/workspaces-ui-react/README.md
* Added support for remote application stores
* Extended plugins with limited access to the controllers
* glue42core is now set as quickly as possible
> Implement Remote Stores For Applications

- packages/workspaces-ui-core/src/componentStateMonitor.ts
- packages/workspaces-ui-core/src/layout/controller.ts
- packages/workspaces-ui-core/src/manager.ts
- packages/workspaces-ui-react/src/defaultComponents/WorkspaceContents.tsx
- packages/workspaces-ui-react/src/types/internal.ts
Fixes a problem which occurs when using conditional rendering with the WorkspaceContents component
> Extend the workspace contents component

- packages/workspaces-api/src/controllers/base.ts
- packages/workspaces-api/src/controllers/main.ts
- packages/workspaces-api/src/models/window.ts
- packages/workspaces-api/src/models/workspace.ts
- packages/workspaces-api/src/types/controller.ts
- packages/workspaces-api/workspaces.d.ts
> Fixes the workspace windows reference refresh

- e2e/tests/workspaces/Workspace/saveLayout.spec.js
- packages/workspaces-ui-core/src/layouts.ts
Signed-off-by: Svetozar Mateev <svetozar.mateev@gmail.com>
> added empty object as default value

- tutorials/javascript/start/Clients/index.html
*Add missing id attribute to button element to prevent the following error
> bugfix: js-tutorial

- e2e/tests/workspaces/API/restoreWorkspace.spec.js
- e2e/tests/workspaces/Frame/constraints.spec.js
- e2e/tests/workspaces/Parent/addColumn.spec.js
- e2e/tests/workspaces/Parent/addGroup.spec.js
- e2e/tests/workspaces/Parent/addRow.spec.js
- e2e/tests/workspaces/Parent/addWindow.spec.js
- e2e/tests/workspaces/Parent/properties.spec.js
- e2e/tests/workspaces/Workspace/addColumn.spec.js
- e2e/tests/workspaces/Workspace/addGroup.spec.js
- e2e/tests/workspaces/Workspace/properties.spec.js
- e2e/tests/workspaces/WorkspaceWindow/properties.spec.js
- packages/dev-workspaces-frame/package-lock.json
- packages/dev-workspaces-frame/package.json
- packages/golden-layout/changelog.md
- packages/golden-layout/src/js/config/defaultConfig.js
- packages/golden-layout/src/js/items/RowOrColumn.js
- packages/workspaces-ui-core/assets/css/goldenlayout-base.css
- packages/workspaces-ui-core/changelog.md
- packages/workspaces-ui-core/src/utils/constants.ts
Improved the pinned behavior in Workspaces by adding a target size which the element will use as a fixed size when recovering from an invalid width or height. Also added new default minimum size(20) to improve the UX.
> Improved the pinned behaviour and made a few minor improvements

- packages/core/glue.d.ts
- packages/web/web.d.ts
- packages/workspaces-api/workspaces.d.ts
> Fixed API descriptions and links.

- packages/fdc3/src/agent.ts
Add validation to `raiseIntentForContext()`
> Fix an issue with the validation of `raiseIntent()`

- packages/core/glue.d.ts
- packages/web/web.d.ts
> Fixed @ symbols and links in package descriptions

- packages/web-platform/src/controllers/serviceWorker.ts
- packages/web-platform/src/libs/notifications/controller.ts
- packages/web-platform/src/libs/notifications/decoders.ts
- packages/web-platform/src/libs/notifications/types.ts
- packages/web-worker/src/worker.ts
- packages/web/src/shared/decoders.ts
- packages/web/web.d.ts
> Added an option to focus the platform on default click of the notification

- e2e/tests/workspaces/Parent/addColumn.spec.js
- e2e/tests/workspaces/Parent/addGroup.spec.js
- e2e/tests/workspaces/Parent/addRow.spec.js
- e2e/tests/workspaces/Parent/addWindow.spec.js
- e2e/tests/workspaces/Parent/maximize.spec.js
- e2e/tests/workspaces/Parent/restore.spec.js
- packages/golden-layout/changelog.md
- packages/golden-layout/src/js/LayoutManager.js
- packages/golden-layout/src/js/controls/Tab.js
- packages/workspaces-api/changelog.md
- packages/workspaces-api/src/models/base/base.ts
- packages/workspaces-api/src/models/column.ts
- packages/workspaces-api/src/models/group.ts
- packages/workspaces-api/src/models/row.ts
- packages/workspaces-api/src/types/protocol.ts
- packages/workspaces-ui-core/assets/css/glue42-theme.css
- packages/workspaces-ui-core/assets/css/goldenlayout-base.css
- packages/workspaces-ui-core/changelog.md
- packages/workspaces-ui-core/src/config/converter.ts
- packages/workspaces-ui-core/src/iframeController.ts
- packages/workspaces-ui-core/src/layout/controller.ts
- packages/workspaces-ui-core/src/layout/eventEmitter.ts
- packages/workspaces-ui-core/src/manager.ts
- packages/workspaces-ui-core/src/state/containerWrapper.ts
- packages/workspaces-ui-core/src/state/resolver.ts
- packages/workspaces-ui-core/src/state/workspaceWrapper.ts
- packages/workspaces-ui-core/src/types/internal.ts
- packages/workspaces-ui-core/test/config/converter/convertToAPIConfig.spec.ts
This features enables workspaces to maximize not only windows, but also groups, rows and columns.
- **Group**
isMaximized -  indicates whether the group is maximized
maximize() - maximize the group
restore()- restore the group from maximized state
- **Row**
isMaximized -  indicates whether the row is maximized
maximize() - maximize the row 
restore()- restore the row from maximized state
- **Column**
isMaximized -  indicates whether the column is maximized
maximize() - maximize the column
restore()- restore the column from maximized state
> Implement container maximization in workspaces

- e2e/tests/workspaces/Frame/onWorkspaceSelected.spec.js
- e2e/tests/workspaces/Workspace/properties.spec.js
- packages/web-platform/changelog.md
- packages/web-platform/src/libs/workspaces/decoders.ts
- packages/workspaces-api/changelog.md
- packages/workspaces-api/src/controllers/base.ts
- packages/workspaces-api/src/models/workspace.ts
- packages/workspaces-api/src/shared/decoders.ts
- packages/workspaces-api/src/types/protocol.ts
- packages/workspaces-api/workspaces.d.ts
Added the **isSelected** property to the **Workspace** object.
> Implement workspace is selected property

- e2e/tests/workspaces/API/onWindowAdded.spec.js
- e2e/tests/workspaces/API/onWindowRemoved.spec.js
- packages/workspaces-ui-core/changelog.md
- packages/workspaces-ui-core/src/app/factory.ts
- packages/workspaces-ui-core/src/export.ts
- packages/workspaces-ui-core/src/interop/facade.ts
- packages/workspaces-ui-core/src/layout/controller.ts
- packages/workspaces-ui-core/src/layout/eventEmitter.ts
- packages/workspaces-ui-core/src/manager.ts
- packages/workspaces-ui-core/src/state/resolver.ts
- packages/workspaces-ui-core/src/state/windowWrapper.ts
- onWindowAdded will be invoked when a drag is finished
- onWindowRemoved will be invoked when a drag is stared
> Added onWindowAdded and onWindowRemoved when dragging

- packages/fdc3/src/channels/channels.ts
- packages/fdc3/src/index.ts
- packages/fdc3/src/main.ts
- packages/fdc3/src/types/windowtype.d.ts
- packages/fdc3/src/utils.ts
Renamed electron checks & added glue42EnterpriseConfig global variable
> FDC3 - Browser <> Glue Enterprise support 

- e2e/tests/workspaces/Workspace/saveLayout.spec.js
- packages/workspaces-api/src/models/workspace.ts
- packages/workspaces-api/src/shared/decoders.ts
- packages/workspaces-api/workspaces.d.ts
- packages/workspaces-ui-core/src/interop/facade.ts
- packages/workspaces-ui-core/src/interop/types.ts
- packages/workspaces-ui-core/src/layouts.ts
- packages/workspaces-ui-core/src/manager.ts
- packages/workspaces-ui-core/src/types/internal.ts
Added an optional metadata object to `workspace.saveLayout` and to `glue.workspaces.saveLayout`
> Implemented the option

- packages/workspaces-api/workspaces.d.ts
Replaced the types represented by inline objects with interfaces, so the documentation generator can visualize them better.
> Updated the typings to be more documentation friendly

- packages/core/src/contexts/bridges/gw3/bridge.ts
- packages/core/src/contexts/bridges/gw3/contextData.ts
Signed-off-by: Velko Nikolov <velko.nikolov@tick42.com>
> G4E-4838 - fix race condition between get and subscribe - zendesk568

- tutorials/guides/02_react/react.md
It seems that there is no Chapter 1.5, the instructions are in Chapter 1.4
> Typo fix - changed chapter 1.5 to 1.4

- tutorials/guides/02_react/react.md
There is no name property in client, notifications come as "A new Workspace for undefined was opened!"
> Client name fix

- e2e/tests/contexts/set.spec.js
- e2e/tests/contexts/update.spec.js
- packages/core/src/contexts/bridges/gw3/bridge.ts
- packages/core/tests/contexts/complex-update.ts
See https://jira.tick42.com/browse/G4E-6142
> G4E-6142 - fix referential mutation bug in context.update()
