Glue42/core

- packages/core/glue.d.ts
- packages/core/src/index.ts
- packages/core/src/metrics/protocols/gw3/gw3.ts
- packages/core/src/metrics/types.ts
- packages/core/src/types.ts
Users need to be able to control (stop/start) the metrics being published by JS applications. This needs to be done dynamically.
Acceptance Criteria
1. Select application 
2. Run instance, Metrics Viewer and verify you can see metrics from the selected application;
5. Disable metrics publishing; look at the Metrics Viewer and check that there are NO updated (e.g. in FAV metric section ) from our instance;
6. Enable metrics publishing - FAV metric for the selected app in Metrics Viewer should be publishing updates again.
> stop publishing metrics at runtime

- packages/cli-core/package-lock.json
- packages/cli-core/src/builder/controller.ts
- packages/cli-core/src/cli.ts
- packages/cli-core/src/commands.ts
- packages/cli-core/src/config/cli.config.d.ts
- packages/cli-core/src/config/config-decoders.ts
- packages/cli-core/src/config/controller.ts
- packages/cli-core/src/config/user.config.d.ts
- packages/cli-core/src/defaults.ts
- packages/cli-core/src/initiate/controller.ts
- packages/cli-core/src/initiate/index.ts
- packages/cli-core/src/server/server.ts
- packages/cli-core/src/workspaces/controller.ts
- packages/cli-core/src/workspaces/index.ts
added:
gluec init -w (sets up a new Glue42 Core environment with workspaces)
gluec workspaces init (adds workspaces to an existing Glue42 Core environment)
extended:
gluec serve (now is aware if workspaces are initialized and serves those assets too)
gluec build (now is aware if workspaces are initialized and build those assets too)
> Extend the CLI with workspaces functionalities

- docs/core/03_capabilities/99_fdc3-compliance/fdc3-compliance.md
- live-examples/app-manager/app-manager-events/app-b/index.js
- packages/fdc3/src/channels/channels.ts
- packages/fdc3/src/main.ts
- packages/fdc3/src/utils.ts
- packages/fdc3/src/windowtype.d.ts
Fix an issue where the context was updated an additional time
Update the @glue42/fdc3 package versioning
Remove the usage of `glue.channels.list()` for backwards compatibility
Use the auto injected Glue factory function when it is available
Fix an issue with `decorateContextApi()`
Display the newly opened/closed application name inside of the AppManager live example
Update the FDC3 documentation
> Add a way for @glue42/fdc3 to accept the application's name

- packages/web/src/channels/contexts.ts
- packages/web/src/channels/main.ts
Fix an issue where using @glue42/core@5.2.0 deletes all channels' contexts on initialization
Remove an unnecessary call to `this.get(name)` that slowed publishing to a channel
> Use `glue.contexts.setPaths()` instead of `glue.contexts.update()` when updating a channel

- docs/core/04_core-concepts/03_glue42-client/03_react/react.md
- e2e/tests/channels/API/join.spec.js
- packages/core/src/contexts/contextsModule.ts
- packages/web/src/channels/main.ts
- packages/web/web.d.ts
Fix an issue inside the Channels API where join fired the subscribe callbacks before the new current channel had been set and add a test that covers the case
Make the url of the CreateOptions type optional
Fix a typo inside the Glue42 Core React documentation
> Add input validation to the @glue42/core's Contexts API

- packages/fdc3/package-lock.json
- packages/fdc3/package.json
- packages/fdc3/src/agent.ts
- packages/fdc3/src/channels/channels.ts
- packages/fdc3/src/utils.ts
- packages/ng/package-lock.json
- packages/ng/package.json
- packages/react-hooks/package-lock.json
- packages/react-hooks/package.json
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/intents/main.ts
- packages/web/src/intents/types.ts
- packages/web/src/shared/decoders/app-manager.ts
- packages/web/src/shared/decoders/intents.ts
- packages/web/src/types.ts
- packages/web/src/web.ts
- packages/web/web.d.ts
Instantiate AppManager always as Intents depends on it, but only attach it to the glue object when the user passes appManager: true
Use the @glue42/web Intents API for the @glue42/fdc3 Glue42Core implementation
Bump to @glue42/desktop@5.2.1
Add decoder validation for the Intents API
Change `raise()` to default to "reuse" in the case of a dynamic intent
> Implement an Intents API (TODO: Tests, Typings explanation, Documentation, Live examples and Tutorial)

- docs/core/03_capabilities/02_application-management/application-management.md
- docs/core/03_capabilities/99_fdc3-compliance/fdc3-compliance.md
- docs/core/04_core-concepts/02_environment/01_overview/overview.md
- packages/web/src/app-manager/main.ts
- packages/web/src/glue.config.d.ts
- packages/web/src/layouts/stores/json.ts
- packages/web/src/utils/index.ts
Change the `fetchTimeout()`'s default timeoutMilliseconds from 1000 to 3000
> Add an optional requestTimeout property to the RemoteSource interface

- packages/golden-layout/src/js/controls/Tab.js
- packages/workspaces-ui-core/assets/css/goldenlayout-base.css
- packages/workspaces-ui-react/src/defaultComponents/popups/addApplication/AddApplicationPopup.tsx
- packages/workspaces-ui-react/src/defaultComponents/popups/addApplication/ApplicationsList.tsx
- packages/workspaces-ui-react/src/types/internal.ts
- The bug was that the tabs could not be dragged in the layout
- Added filtering logic for the AddApplicationPopup
**This PR introduces the requirement for `customProperties.includeInWorkspaces` flag in the application definitions in order to appear in the AddApplicationPopup**
> Workspaces extensions improvements

- e2e/config/apps/coreSupport/index.js
- e2e/config/gtf/app.ts
- e2e/config/gtf/config.ts
- e2e/tests/intents/API/addIntentListener.spec.js
- e2e/tests/intents/API/all.spec.js
- e2e/tests/intents/API/find.spec.js
- e2e/tests/intents/API/raise.spec.js
- packages/web/src/intents/controller.ts
Fix an issue where `addIntentListener()` initially allows the addition of a second listener for the same intent
> Add tests for all intents methods

- docs/core/03_capabilities/99_fdc3-compliance/fdc3-compliance.md
- packages/fdc3/package-lock.json
- packages/fdc3/package.json
- packages/fdc3/src/agent.ts
- packages/fdc3/src/main.ts
- packages/fdc3/src/types/glue42FDC3DesktopAgent.d.ts
- packages/fdc3/src/types/remoteSource.d.ts
- packages/fdc3/src/types/windowtype.d.ts
- packages/fdc3/src/utils.ts
- packages/fdc3/types.d.ts
Update the documentation
Fix an issue where `addIntentListener()` and `raiseIntent()` used the FDC3 Context type instead of the Glue42 one
> Adapt @glue42/fdc3 (and fdc3-demos) for Glue42 Core v2

- packages/core/src/interop/client/client.ts
- packages/core/src/interop/client/repository.ts
- packages/core/src/interop/instance.ts
- packages/core/src/interop/interop.ts
- packages/core/tests/interop/methods.ts
Short-circuit x2 frequently used `containsProps()` method
Fix a broken @glue42/core test
NOTE: Once this PR is merged un-skip and rename the Interop tests whose name includes `PR: https://github.com/Glue42/core/pull/158`.
> Replace a static API InstanceWrapper property with an injected API

- e2e/tests/interop/API/methodAdded.spec.js
- e2e/tests/interop/API/methodRemoved.spec.js
- e2e/tests/interop/API/methods.spec.js
- e2e/tests/interop/API/servers.spec.js
- e2e/tests/interop/API/subscribe.spec.js
- e2e/tests/interop/Instance/getMethods.spec.js
- e2e/tests/interop/Instance/getStreams.spec.js
- e2e/tests/interop/MethodDefinition/properties.spec.js
- packages/core/glue.d.ts
- packages/core/src/contexts/helpers.ts
- packages/core/src/interop/client/client.ts
- packages/core/src/interop/client/repository.ts
- packages/core/src/interop/protocols/gw3/server.ts
- packages/core/src/interop/server/stream.ts
- packages/web-platform/src/libs/intents/controller.ts
- packages/web/src/intents/controller.ts
Nest the client flags inside of a `metadata` flag
Update `containsProps()` to consider the flags when filtering using `methods()` and `servers()`
Update the Intents API to use the flags instead of the description to store Intent metadata
Add Interop e2e tests for flags
Unskip tests related to #158
Correctly clean up inside of the `subscribe()` tests
> Change flags to be a string => any mapping (instead of string => string)

- packages/golden-layout/src/js/controls/Tab.js
- packages/workspaces-ui-core/src/export.ts
- packages/workspaces-ui-core/src/iframeController.ts
- packages/workspaces-ui-core/src/manager.ts
- packages/workspaces-ui-core/workspaces.d.ts
- packages/workspaces-ui-react/src/defaultComponents/popups/addApplication/ApplicationsList.tsx
- packages/workspaces-ui-react/src/index.tsx
- packages/workspaces-ui-react/src/types/internal.ts
- packages/workspaces-ui-react/src/workspacesManager.ts
Added `requestFocus()` which should be used when the frame is running in Glue42Desktop and custom elements that require focus are stopping the propagation of `mousedown` and `pointerdown`.
> Added requestFocus() in workspaces-ui-react

- e2e/config/apps/noGlueApp/index.html
- e2e/tests/workspaces/API/createWorkspace.spec.js
- e2e/tests/workspaces/API/restoreWorkspace.spec.js
- e2e/tests/workspaces/Frame/onWindowLoaded.spec.js
- e2e/tests/workspaces/Workspace/saveLayout.spec.js
- packages/golden-layout/index.d.ts
- packages/web-platform/src/libs/workspaces/controller.ts
- packages/web-platform/src/libs/workspaces/types.ts
- packages/workspaces-api/src/shared/decoders.ts
- packages/workspaces-api/workspaces.d.ts
- packages/workspaces-ui-core/src/interop/facade.ts
- packages/workspaces-ui-core/src/interop/types.ts
- packages/workspaces-ui-core/src/layout/controller.ts
- packages/workspaces-ui-core/src/layouts.ts
- packages/workspaces-ui-core/src/manager.ts
- packages/workspaces-ui-core/src/store.ts
- packages/workspaces-ui-core/src/types/internal.ts
Added the option to pass a `reuseWorkspaceId` parameter that changes the targeted workspace contents without closing  and reopening the workspace through `createWorkspace` and `restoreWorkspace`
> Implement reuse workspace id

- packages/fdc3/src/channels/channels.ts
- packages/web-platform/src/libs/intents/controller.ts
- packages/web/src/intents/controller.ts
Omit the intent name from the intent metadata
Return null inside of `getCurrentChannel()` when the app is not joined to a channel
> Nest the intent metadata inside a intent property of the method flags

- tutorials/guides/02_core/01_javascript/javascript.md
* `createChannelSelectorWidget` returns a function, not a promise,
so there's no need to to `await createChannelSelectorWidget(..)`
in the tutorial.
> docs: update creation of channel selector widget

- tutorials/javascript/start/package.json
Going through the JS tutorial I found it frustrating when I would make changes to an html or javascript file, only to have the changes fail to appear in the browser because the browser was caching the documents. This PR uses an http-server configuration option to prevent caching of files. As a result, after making changes to an html or javascript file you only need to refresh the browser and the changes will automatically appear.
see cache-control headers:
> reconfigure js tutorial server to prevent caching

- packages/core/src/index.ts
Тhe DevTools/PerformanceTracker application needs this data in order to work both with the new data format and with older version.
> Glue performance events backwards compatibility fix

- packages/workspaces-api/changelog.md
- packages/workspaces-api/src/controllers/base.ts
- packages/workspaces-api/src/controllers/main.ts
- packages/workspaces-api/src/main.ts
- packages/workspaces-api/src/models/frame.ts
- packages/workspaces-api/src/shared/decoders.ts
- packages/workspaces-api/src/types/controller.ts
- packages/workspaces-api/src/types/protocol.ts
- packages/workspaces-ui-core/changelog.md
- packages/workspaces-ui-core/src/export.ts
- packages/workspaces-ui-core/src/layout/controller.ts
- packages/workspaces-ui-core/src/manager.ts
- packages/workspaces-ui-core/src/types/events.ts
Improved the event flow so the case in which the workspaces frame is a platform and there is an attempt to close the last workspace can be detected from a user using the API.
Issue for reference #234
> Improve workspace events when the frame is a platform

- e2e/config/gtf/index.ts
- e2e/tests/notifications/getPermission.spec.js
- e2e/tests/notifications/raise.spec.js
- e2e/tests/notifications/requestPermission.spec.js
- packages/web-platform/changelog.md
- packages/web-platform/src/libs/notifications/controller.ts
- packages/web-platform/src/libs/notifications/decoders.ts
- packages/web-platform/src/libs/notifications/types.ts
- packages/web/changelog.md
- packages/web/src/notifications/controller.ts
- packages/web/src/notifications/protocol.ts
- packages/web/src/shared/decoders.ts
- packages/web/web.d.ts
glue.notifications.getPermission() returns the native browser permission level of the platform, to which the client is connected and is therefore responsible for raising browser notification toasts. The permissions levels are the standard levels as defined in the web standard:
- "denied"
- "default"
- "granted"
> Added a GetPermission method to the Notifications API
